// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: graphql/schema.proto

package graphqlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nullability int32

const (
	Nullability_NULLABILITY_UNSPECIFIED Nullability = 0
	Nullability_NULLABLE                Nullability = 1
	Nullability_NON_NULL                Nullability = 2
)

// Enum value maps for Nullability.
var (
	Nullability_name = map[int32]string{
		0: "NULLABILITY_UNSPECIFIED",
		1: "NULLABLE",
		2: "NON_NULL",
	}
	Nullability_value = map[string]int32{
		"NULLABILITY_UNSPECIFIED": 0,
		"NULLABLE":                1,
		"NON_NULL":                2,
	}
)

func (x Nullability) Enum() *Nullability {
	p := new(Nullability)
	*p = x
	return p
}

func (x Nullability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Nullability) Descriptor() protoreflect.EnumDescriptor {
	return file_graphql_schema_proto_enumTypes[0].Descriptor()
}

func (Nullability) Type() protoreflect.EnumType {
	return &file_graphql_schema_proto_enumTypes[0]
}

func (x Nullability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Nullability.Descriptor instead.
func (Nullability) EnumDescriptor() ([]byte, []int) {
	return file_graphql_schema_proto_rawDescGZIP(), []int{0}
}

type GraphqlSchemaOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypePrefix      string `protobuf:"bytes,1,opt,name=type_prefix,json=typePrefix,proto3" json:"type_prefix,omitempty"`
	IgnoreRequests  bool   `protobuf:"varint,2,opt,name=ignore_requests,json=ignoreRequests,proto3" json:"ignore_requests,omitempty"`
	IgnoreResponses bool   `protobuf:"varint,3,opt,name=ignore_responses,json=ignoreResponses,proto3" json:"ignore_responses,omitempty"`
	Ignore          bool   `protobuf:"varint,4,opt,name=ignore,proto3" json:"ignore,omitempty"`
}

func (x *GraphqlSchemaOptions) Reset() {
	*x = GraphqlSchemaOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_schema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphqlSchemaOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlSchemaOptions) ProtoMessage() {}

func (x *GraphqlSchemaOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_schema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlSchemaOptions.ProtoReflect.Descriptor instead.
func (*GraphqlSchemaOptions) Descriptor() ([]byte, []int) {
	return file_graphql_schema_proto_rawDescGZIP(), []int{0}
}

func (x *GraphqlSchemaOptions) GetTypePrefix() string {
	if x != nil {
		return x.TypePrefix
	}
	return ""
}

func (x *GraphqlSchemaOptions) GetIgnoreRequests() bool {
	if x != nil {
		return x.IgnoreRequests
	}
	return false
}

func (x *GraphqlSchemaOptions) GetIgnoreResponses() bool {
	if x != nil {
		return x.IgnoreResponses
	}
	return false
}

func (x *GraphqlSchemaOptions) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

type GraphqlObjectTypeOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Do not generate GraphQL Object and Input. Nested types will not be ignored.
	Ignore bool `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// If `squash_union` is true, the message is converted to `union` instead of object type.
	//
	// ```proto
	// message Content {
	//   option (graphql.object_type).squash_union = true;
	//   oneof content {
	//     Blog blog = 2;
	//     Video video = 2;
	//   }
	// }
	// ```
	//
	// ```grahpql
	// union Content = Blog | Video
	// ```
	SquashUnion bool `protobuf:"varint,2,opt,name=squash_union,json=squashUnion,proto3" json:"squash_union,omitempty"`
	// If `interface` is true, the message is converted to `interface` instead of object type.
	Interface bool `protobuf:"varint,3,opt,name=interface,proto3" json:"interface,omitempty"`
	// Specify a object name in GraphQL. If do not specified, use the same as a Protobuf message field name.
	//
	// ```proto
	// message Foo {
	//   option (graphql.object_type).name = "Bar"
	//   // ...
	// }
	// ````
	//
	// ```grahpql
	// object Bar {
	//   # ...
	// }
	// ```
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GraphqlObjectTypeOptions) Reset() {
	*x = GraphqlObjectTypeOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_schema_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphqlObjectTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlObjectTypeOptions) ProtoMessage() {}

func (x *GraphqlObjectTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_schema_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlObjectTypeOptions.ProtoReflect.Descriptor instead.
func (*GraphqlObjectTypeOptions) Descriptor() ([]byte, []int) {
	return file_graphql_schema_proto_rawDescGZIP(), []int{1}
}

func (x *GraphqlObjectTypeOptions) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

func (x *GraphqlObjectTypeOptions) GetSquashUnion() bool {
	if x != nil {
		return x.SquashUnion
	}
	return false
}

func (x *GraphqlObjectTypeOptions) GetInterface() bool {
	if x != nil {
		return x.Interface
	}
	return false
}

func (x *GraphqlObjectTypeOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GraphqlInputTypeOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Do not always generate partial input types.
	NoPartial bool `protobuf:"varint,1,opt,name=no_partial,json=noPartial,proto3" json:"no_partial,omitempty"`
	// Do not generate GraphQL Input. Nested types will not be ignored.
	Ignore bool `protobuf:"varint,2,opt,name=ignore,proto3" json:"ignore,omitempty"`
}

func (x *GraphqlInputTypeOptions) Reset() {
	*x = GraphqlInputTypeOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_schema_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphqlInputTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlInputTypeOptions) ProtoMessage() {}

func (x *GraphqlInputTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_schema_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlInputTypeOptions.ProtoReflect.Descriptor instead.
func (*GraphqlInputTypeOptions) Descriptor() ([]byte, []int) {
	return file_graphql_schema_proto_rawDescGZIP(), []int{2}
}

func (x *GraphqlInputTypeOptions) GetNoPartial() bool {
	if x != nil {
		return x.NoPartial
	}
	return false
}

func (x *GraphqlInputTypeOptions) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

type GraphqlFieldOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ignore bool `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// Specify a field name in GraphQL. If do not specified, use the same as a Protobuf message field name.
	//
	// ```proto
	// message User {
	//   // Required. Output only.
	//   uint64 id = 1 [(graphql.field).name = "databaseId"];
	// }
	// ````
	//
	// ```grahpql
	// object User {
	//   databaseId: String!
	// }
	// ```
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Omit resolver implementation in code generation.
	SkipResolver bool `protobuf:"varint,3,opt,name=skip_resolver,json=skipResolver,proto3" json:"skip_resolver,omitempty"`
	// Use ID type.
	//
	// ```proto
	// message User {
	//   // Required. Output only.
	//   uint64 id = 1 [(graphql.field).id = true];
	// }
	// ````
	//
	// ```grahpql
	// object User {
	//   id: ID!
	// }
	// ```
	Id bool `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	// Indicates the nullability of the output for a given field.
	OutputNullability Nullability `protobuf:"varint,11,opt,name=output_nullability,json=outputNullability,proto3,enum=graphql.Nullability" json:"output_nullability,omitempty"`
	// Indicates the nullability of the input for a given field.
	InputNullability Nullability `protobuf:"varint,12,opt,name=input_nullability,json=inputNullability,proto3,enum=graphql.Nullability" json:"input_nullability,omitempty"`
	// Indicates the nullability of the partial input for a given field.
	PartialInputNullability Nullability `protobuf:"varint,13,opt,name=partial_input_nullability,json=partialInputNullability,proto3,enum=graphql.Nullability" json:"partial_input_nullability,omitempty"`
}

func (x *GraphqlFieldOptions) Reset() {
	*x = GraphqlFieldOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_schema_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphqlFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlFieldOptions) ProtoMessage() {}

func (x *GraphqlFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_schema_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlFieldOptions.ProtoReflect.Descriptor instead.
func (*GraphqlFieldOptions) Descriptor() ([]byte, []int) {
	return file_graphql_schema_proto_rawDescGZIP(), []int{3}
}

func (x *GraphqlFieldOptions) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

func (x *GraphqlFieldOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GraphqlFieldOptions) GetSkipResolver() bool {
	if x != nil {
		return x.SkipResolver
	}
	return false
}

func (x *GraphqlFieldOptions) GetId() bool {
	if x != nil {
		return x.Id
	}
	return false
}

func (x *GraphqlFieldOptions) GetOutputNullability() Nullability {
	if x != nil {
		return x.OutputNullability
	}
	return Nullability_NULLABILITY_UNSPECIFIED
}

func (x *GraphqlFieldOptions) GetInputNullability() Nullability {
	if x != nil {
		return x.InputNullability
	}
	return Nullability_NULLABILITY_UNSPECIFIED
}

func (x *GraphqlFieldOptions) GetPartialInputNullability() Nullability {
	if x != nil {
		return x.PartialInputNullability
	}
	return Nullability_NULLABILITY_UNSPECIFIED
}

type GraphqlOneofOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ignore bool `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
}

func (x *GraphqlOneofOptions) Reset() {
	*x = GraphqlOneofOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_schema_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphqlOneofOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlOneofOptions) ProtoMessage() {}

func (x *GraphqlOneofOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_schema_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlOneofOptions.ProtoReflect.Descriptor instead.
func (*GraphqlOneofOptions) Descriptor() ([]byte, []int) {
	return file_graphql_schema_proto_rawDescGZIP(), []int{4}
}

func (x *GraphqlOneofOptions) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

type GraphqlEnumOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ignore bool `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
}

func (x *GraphqlEnumOptions) Reset() {
	*x = GraphqlEnumOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_schema_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphqlEnumOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlEnumOptions) ProtoMessage() {}

func (x *GraphqlEnumOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_schema_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlEnumOptions.ProtoReflect.Descriptor instead.
func (*GraphqlEnumOptions) Descriptor() ([]byte, []int) {
	return file_graphql_schema_proto_rawDescGZIP(), []int{5}
}

func (x *GraphqlEnumOptions) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

type GraphqlEnumValueOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ignore bool `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
}

func (x *GraphqlEnumValueOptions) Reset() {
	*x = GraphqlEnumValueOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graphql_schema_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphqlEnumValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlEnumValueOptions) ProtoMessage() {}

func (x *GraphqlEnumValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_graphql_schema_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlEnumValueOptions.ProtoReflect.Descriptor instead.
func (*GraphqlEnumValueOptions) Descriptor() ([]byte, []int) {
	return file_graphql_schema_proto_rawDescGZIP(), []int{6}
}

func (x *GraphqlEnumValueOptions) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

var file_graphql_schema_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*GraphqlSchemaOptions)(nil),
		Field:         2056,
		Name:          "graphql.schema",
		Tag:           "bytes,2056,opt,name=schema",
		Filename:      "graphql/schema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*GraphqlObjectTypeOptions)(nil),
		Field:         2056,
		Name:          "graphql.object_type",
		Tag:           "bytes,2056,opt,name=object_type",
		Filename:      "graphql/schema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*GraphqlInputTypeOptions)(nil),
		Field:         2057,
		Name:          "graphql.input_type",
		Tag:           "bytes,2057,opt,name=input_type",
		Filename:      "graphql/schema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*GraphqlFieldOptions)(nil),
		Field:         2056,
		Name:          "graphql.field",
		Tag:           "bytes,2056,opt,name=field",
		Filename:      "graphql/schema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*GraphqlOneofOptions)(nil),
		Field:         2056,
		Name:          "graphql.oneof",
		Tag:           "bytes,2056,opt,name=oneof",
		Filename:      "graphql/schema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*GraphqlEnumOptions)(nil),
		Field:         2056,
		Name:          "graphql.enum_type",
		Tag:           "bytes,2056,opt,name=enum_type",
		Filename:      "graphql/schema.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*GraphqlEnumValueOptions)(nil),
		Field:         2056,
		Name:          "graphql.enum_value",
		Tag:           "bytes,2056,opt,name=enum_value",
		Filename:      "graphql/schema.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional graphql.GraphqlSchemaOptions schema = 2056;
	E_Schema = &file_graphql_schema_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional graphql.GraphqlObjectTypeOptions object_type = 2056;
	E_ObjectType = &file_graphql_schema_proto_extTypes[1]
	// optional graphql.GraphqlInputTypeOptions input_type = 2057;
	E_InputType = &file_graphql_schema_proto_extTypes[2]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional graphql.GraphqlFieldOptions field = 2056;
	E_Field = &file_graphql_schema_proto_extTypes[3]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// optional graphql.GraphqlOneofOptions oneof = 2056;
	E_Oneof = &file_graphql_schema_proto_extTypes[4]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional graphql.GraphqlEnumOptions enum_type = 2056;
	E_EnumType = &file_graphql_schema_proto_extTypes[5]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional graphql.GraphqlEnumValueOptions enum_value = 2056;
	E_EnumValue = &file_graphql_schema_proto_extTypes[6]
)

var File_graphql_schema_proto protoreflect.FileDescriptor

var file_graphql_schema_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x1a,
	0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xa3, 0x01, 0x0a, 0x14, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x79,
	0x70, 0x65, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x74, 0x79, 0x70, 0x65, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x27, 0x0a, 0x0f, 0x69,
	0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f,
	0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x18, 0x47, 0x72, 0x61, 0x70,
	0x68, 0x71, 0x6c, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x73, 0x71, 0x75, 0x61, 0x73, 0x68, 0x5f, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x73, 0x71, 0x75, 0x61, 0x73, 0x68, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x50, 0x0a, 0x17, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x6e, 0x6f, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x6e, 0x6f, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x67, 0x6e, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x67, 0x6e,
	0x6f, 0x72, 0x65, 0x22, 0xd0, 0x02, 0x0a, 0x13, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x67, 0x6e, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x67, 0x6e,
	0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x6b, 0x69, 0x70, 0x5f,
	0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c,
	0x73, 0x6b, 0x69, 0x70, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x69, 0x64, 0x12, 0x43, 0x0a, 0x12,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x71, 0x6c, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x11,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x12, 0x41, 0x0a, 0x11, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x52, 0x10, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x12, 0x50, 0x0a, 0x19, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x5f,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71,
	0x6c, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x17, 0x70,
	0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x4e, 0x75, 0x6c, 0x6c, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x2d, 0x0a, 0x13, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71,
	0x6c, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69,
	0x67, 0x6e, 0x6f, 0x72, 0x65, 0x22, 0x2c, 0x0a, 0x12, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c,
	0x45, 0x6e, 0x75, 0x6d, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x67, 0x6e, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x67, 0x6e,
	0x6f, 0x72, 0x65, 0x22, 0x31, 0x0a, 0x17, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x45, 0x6e,
	0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x2a, 0x46, 0x0a, 0x0b, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x17, 0x4e, 0x55, 0x4c, 0x4c, 0x41, 0x42, 0x49,
	0x4c, 0x49, 0x54, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x55, 0x4c, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01,
	0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x4e, 0x5f, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x02, 0x3a, 0x54,
	0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x88, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x06, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x3a, 0x64, 0x0a, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x88, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0a,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x3a, 0x61, 0x0a, 0x0a, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x89, 0x10, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68,
	0x71, 0x6c, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x3a, 0x52, 0x0a,
	0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x88, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x3a, 0x52, 0x0a, 0x05, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4f, 0x6e, 0x65,
	0x6f, 0x66, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x88, 0x10, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68,
	0x71, 0x6c, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05,
	0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x3a, 0x57, 0x0a, 0x09, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x88, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71,
	0x6c, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x08, 0x65, 0x6e, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x3a, 0x63,
	0x0a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x88, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c,
	0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x09, 0x65, 0x6e, 0x75, 0x6d, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x2f, 0x67, 0x6f,
	0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x71, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_graphql_schema_proto_rawDescOnce sync.Once
	file_graphql_schema_proto_rawDescData = file_graphql_schema_proto_rawDesc
)

func file_graphql_schema_proto_rawDescGZIP() []byte {
	file_graphql_schema_proto_rawDescOnce.Do(func() {
		file_graphql_schema_proto_rawDescData = protoimpl.X.CompressGZIP(file_graphql_schema_proto_rawDescData)
	})
	return file_graphql_schema_proto_rawDescData
}

var file_graphql_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_graphql_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_graphql_schema_proto_goTypes = []interface{}{
	(Nullability)(0),                      // 0: graphql.Nullability
	(*GraphqlSchemaOptions)(nil),          // 1: graphql.GraphqlSchemaOptions
	(*GraphqlObjectTypeOptions)(nil),      // 2: graphql.GraphqlObjectTypeOptions
	(*GraphqlInputTypeOptions)(nil),       // 3: graphql.GraphqlInputTypeOptions
	(*GraphqlFieldOptions)(nil),           // 4: graphql.GraphqlFieldOptions
	(*GraphqlOneofOptions)(nil),           // 5: graphql.GraphqlOneofOptions
	(*GraphqlEnumOptions)(nil),            // 6: graphql.GraphqlEnumOptions
	(*GraphqlEnumValueOptions)(nil),       // 7: graphql.GraphqlEnumValueOptions
	(*descriptorpb.FileOptions)(nil),      // 8: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil),   // 9: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),     // 10: google.protobuf.FieldOptions
	(*descriptorpb.OneofOptions)(nil),     // 11: google.protobuf.OneofOptions
	(*descriptorpb.EnumOptions)(nil),      // 12: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 13: google.protobuf.EnumValueOptions
}
var file_graphql_schema_proto_depIdxs = []int32{
	0,  // 0: graphql.GraphqlFieldOptions.output_nullability:type_name -> graphql.Nullability
	0,  // 1: graphql.GraphqlFieldOptions.input_nullability:type_name -> graphql.Nullability
	0,  // 2: graphql.GraphqlFieldOptions.partial_input_nullability:type_name -> graphql.Nullability
	8,  // 3: graphql.schema:extendee -> google.protobuf.FileOptions
	9,  // 4: graphql.object_type:extendee -> google.protobuf.MessageOptions
	9,  // 5: graphql.input_type:extendee -> google.protobuf.MessageOptions
	10, // 6: graphql.field:extendee -> google.protobuf.FieldOptions
	11, // 7: graphql.oneof:extendee -> google.protobuf.OneofOptions
	12, // 8: graphql.enum_type:extendee -> google.protobuf.EnumOptions
	13, // 9: graphql.enum_value:extendee -> google.protobuf.EnumValueOptions
	1,  // 10: graphql.schema:type_name -> graphql.GraphqlSchemaOptions
	2,  // 11: graphql.object_type:type_name -> graphql.GraphqlObjectTypeOptions
	3,  // 12: graphql.input_type:type_name -> graphql.GraphqlInputTypeOptions
	4,  // 13: graphql.field:type_name -> graphql.GraphqlFieldOptions
	5,  // 14: graphql.oneof:type_name -> graphql.GraphqlOneofOptions
	6,  // 15: graphql.enum_type:type_name -> graphql.GraphqlEnumOptions
	7,  // 16: graphql.enum_value:type_name -> graphql.GraphqlEnumValueOptions
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	10, // [10:17] is the sub-list for extension type_name
	3,  // [3:10] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_graphql_schema_proto_init() }
func file_graphql_schema_proto_init() {
	if File_graphql_schema_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_graphql_schema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphqlSchemaOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_schema_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphqlObjectTypeOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_schema_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphqlInputTypeOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_schema_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphqlFieldOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_schema_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphqlOneofOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_schema_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphqlEnumOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graphql_schema_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphqlEnumValueOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_graphql_schema_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 7,
			NumServices:   0,
		},
		GoTypes:           file_graphql_schema_proto_goTypes,
		DependencyIndexes: file_graphql_schema_proto_depIdxs,
		EnumInfos:         file_graphql_schema_proto_enumTypes,
		MessageInfos:      file_graphql_schema_proto_msgTypes,
		ExtensionInfos:    file_graphql_schema_proto_extTypes,
	}.Build()
	File_graphql_schema_proto = out.File
	file_graphql_schema_proto_rawDesc = nil
	file_graphql_schema_proto_goTypes = nil
	file_graphql_schema_proto_depIdxs = nil
}
