name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job:
          - lint
          - format
          - generate
          - breaking-change
      fail-fast: false
    name: ${{ matrix.job }}
    steps:
      - uses: actions/checkout@v4
      # https://aquaproj.github.io/docs/products/aqua-installer/#-caching
      - uses: actions/cache@v4
        with:
          path: ~/.local/share/aquaproj-aqua
          key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
          restore-keys: |
            v1-aqua-installer-${{runner.os}}-${{runner.arch}}-
      - uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: "v2.30.0"
          aqua_opts: "" # Unset `-l` option
      - uses: bufbuild/buf-lint-action@v1
        if: ${{ matrix.job == 'lint' }}
      - run: |
          buf format --diff --exit-code
        if: ${{ matrix.job == 'format' }}
      - run: |
          buf generate
          git diff --exit-code
        if: ${{ matrix.job == 'generate' }}
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/${{ github.repository }}.git#branch=${{ github.base_ref }}"
        if: ${{ matrix.job == 'breaking-change' && github.event.pull_request }}
